python -m hypothesis.bin.ratio_estimation.train \
    --show \
    --batch-size 1024 \
    --epochs 2 \
    --lr 0.001 \
    --hooks "hooks.add_hooks" \
    --conservativeness 0.00 \
    --data-test "ratio_estimation.DatasetTest" \
    --data-train "ratio_estimation.DatasetTrain" \
    --estimator "ratio_estimation.RatioEstimator" \
    --alpha 0.05
